"""Auto-Generated Regression Test from Fathom Run.

Run Name: Run_3fa85f64
Run ID: 3fa85f64-5717-4562-b3fc-2c963f66afa6
Generated by: Fathom Regression Exporter (Abhishek)
"""

import pytest





if __name__ == "__main__":
    pytest.main([__file__, "-v"])
