"""initial_schema_with_phase0_fixes

Revision ID: 76c608de25f8
Revises: 
Create Date: 2026-10-06 02:14:16.009820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '76c608de25f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trace_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('total_latency_ms', sa.Float(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('has_rewinds', sa.Boolean(), nullable=False),
    sa.Column('active_group_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('span_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('from_span_id', sa.UUID(), nullable=False),
    sa.Column('to_span_id', sa.UUID(), nullable=False),
    sa.Column('link_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['trace_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_span_id', 'to_span_id', 'link_type', name='uq_span_link')
    )
    op.create_index('idx_span_links_run_id', 'span_links', ['run_id'], unique=False)
    op.create_table('trace_spans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('parent_span_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rewind_group_id', sa.UUID(), nullable=True),
    sa.Column('rewind_depth', sa.Integer(), nullable=True),
    sa.Column('origin_span_id', sa.UUID(), nullable=True),
    sa.Column('side_effects', sa.String(length=10), nullable=False),
    sa.Column('llm_request', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['trace_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_spans_embedding', 'trace_spans', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_spans_group', 'trace_spans', ['rewind_group_id'], unique=False)
    op.create_index('idx_spans_origin', 'trace_spans', ['origin_span_id'], unique=False)
    op.create_index('idx_spans_parent', 'trace_spans', ['run_id', 'parent_span_id'], unique=False)
    op.create_index('idx_spans_run_id', 'trace_spans', ['run_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('span_id', sa.UUID(), nullable=False),
    sa.Column('phase', sa.String(length=30), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('evaluator_version', sa.String(length=50), nullable=True),
    sa.Column('evaluator_model', sa.String(length=100), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['span_id'], ['trace_spans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('span_id', 'phase', name='uq_eval_span_phase')
    )
    op.create_index('idx_eval_span_id', 'evaluations', ['span_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_eval_span_id', table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index('idx_spans_run_id', table_name='trace_spans')
    op.drop_index('idx_spans_parent', table_name='trace_spans')
    op.drop_index('idx_spans_origin', table_name='trace_spans')
    op.drop_index('idx_spans_group', table_name='trace_spans')
    op.drop_index('idx_spans_embedding', table_name='trace_spans', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('trace_spans')
    op.drop_index('idx_span_links_run_id', table_name='span_links')
    op.drop_table('span_links')
    op.drop_table('trace_runs')
    # ### end Alembic commands ###
