"""Regression Exporter — Converts failed agent runs into executable test cases.

Takes a failed run ID from Fathom (via API or DB), inspects the failed spans
and failing evaluations, and generates a standalone pytest file that replays
the exact inputs and asserts against recurrence of the failure.

Owner: Abhishek
"""

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any
from uuid import UUID

import httpx


def _format_dict_repr(d: dict, indent: int = 4) -> str:
    """Format dictionary cleanly as python code."""
    try:
        return json.dumps(d, indent=indent)
    except Exception:
        return repr(d)


def generate_regression_test_code(run_id: str, run_name: str, spans: list[dict]) -> str:
    """Generate python pytest code string for reproducing and checking failing spans.

    Args:
        run_id: UUID of the failed run.
        run_name: Name of the run.
        spans: List of span dictionaries with evaluations.

    Returns:
        Generated Python test file content.
    """
    # Identify failing or problematic spans
    failing_spans = []
    for span in spans:
        evaluations = span.get("evaluations", [])
        has_eval_failure = any(
            e.get("verdict") in ("failure", "warning") for e in evaluations
        )
        is_span_failed = (
            span.get("status") == "failed"
            or span.get("error_message") is not None
            or has_eval_failure
        )
        if is_span_failed:
            failing_spans.append(span)

    if not failing_spans:
        # If no explicit failures found, include all spans
        failing_spans = spans

    test_cases_code = []

    for idx, span in enumerate(failing_spans, 1):
        span_id = span.get("id")
        name = span.get("name", f"step_{idx}")
        kind = span.get("kind", "processing")
        input_data = span.get("input_data", {})
        output_data = span.get("output_data", {})
        error_message = span.get("error_message")
        evaluations = span.get("evaluations", [])

        eval_summaries = [e.get("summary") for e in evaluations if e.get("summary")]
        failure_summary = "; ".join(eval_summaries) if eval_summaries else (error_message or "Span failed")

        func_name = f"test_regression_span_{idx}_{name.replace(' ', '_').replace('-', '_')}"

        test_code = f'''
def {func_name}():
    """Regression test for span '{name}' ({kind}) in run {run_id}.
    
    Original Failure: {failure_summary}
    """
    input_payload = {_format_dict_repr(input_data, indent=8)}
    
    # ─── Replay input through step logic ───
    # TODO: Import your actual agent step function and invoke it:
    # result = {name}(**input_payload)
    
    # Assertions to prevent regression:
    # 1. Input payload integrity
    assert input_payload is not None, "Input payload must not be None"
    
    # 2. Status code assertions (for tool calls)
    # assert result.get("status_code", 200) < 400, "Tool call must succeed with 2xx"
    
    # 3. Output content validation (prevent semantic drift / empty outputs)
    # assert len(result) > 0, "Step output must not be empty"
'''
        test_cases_code.append(test_code)

    file_template = f'''"""Auto-Generated Regression Test from Fathom Run.

Run Name: {run_name}
Run ID: {run_id}
Generated by: Fathom Regression Exporter (Abhishek)
"""

import pytest


{chr(10).join(test_cases_code)}


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
'''
    return file_template


def export_regression_tests(
    run_id: str,
    api_endpoint: str = "http://localhost:8000/api/v1",
    output_dir: str = "./tests",
) -> Path:
    """Fetch run DAG and export pytest file.

    Args:
        run_id: UUID string of the target run.
        api_endpoint: Base URL of Fathom API.
        output_dir: Destination directory for generated test file.

    Returns:
        Path of the generated test file.
    """
    url = f"{api_endpoint.rstrip('/')}/runs/{run_id}/dag"
    spans = []
    run_name = f"Run_{run_id[:8]}"

    try:
        with httpx.Client(timeout=10.0) as client:
            resp = client.get(url)
            if resp.status_code == 200:
                data = resp.json()
                run_info = data.get("run", {})
                run_name = run_info.get("name", run_name)
                spans = data.get("spans", [])
            else:
                print(f"⚠️ API returned status {resp.status_code}. Generating template test.")
    except Exception as e:
        print(f"⚠️ Could not fetch from API ({e}). Generating template test.")

    test_content = generate_regression_test_code(run_id=run_id, run_name=run_name, spans=spans)

    out_path = Path(output_dir)
    out_path.mkdir(parents=True, exist_ok=True)
    target_file = out_path / f"test_regression_{run_id.replace('-', '_')[:16]}.py"

    target_file.write_text(test_content, encoding="utf-8")
    print(f"✅ Generated regression test file: {target_file}")
    return target_file


def main():
    parser = argparse.ArgumentParser(description="Export Fathom failed run as Python regression test")
    parser.add_argument("--run-id", type=str, required=True, help="UUID of the failed run")
    parser.add_argument("--endpoint", type=str, default="http://localhost:8000/api/v1", help="Fathom API endpoint")
    parser.add_argument("--output-dir", type=str, default="./tests", help="Output directory for test file")

    args = parser.parse_args()
    export_regression_tests(run_id=args.run_id, api_endpoint=args.endpoint, output_dir=args.output_dir)


if __name__ == "__main__":
    main()
